schema_version: 1

context:
  version: "1.0.1"

package:
  name: ddargparse
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/ddargparse/ddargparse-${{ version }}.tar.gz
  sha256: 3055f45de16c7f87596226da55d887b8294d28bede0e4ffb254fec1b00555592

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12

tests:
  - python:
      imports:
        - ddargparse
      pip_check: true

about:
  summary: Dataclass driven argparse handling
  description: |
    A small Python library that simplifies command-line argument parsing by
    leveraging dataclasses. It allows developers to define their command-line
    interfaces using dataclass fields, making the code more concise and easier
    to maintain. With ddargparse, you can easily create complex command-line
    applications with minimal boilerplate code. It puts a particular focus on
    properly handling type annotations and defaults, minimizing additional
    required annotation and maintaining interoperability with the standard
    argparse.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/koesterlab/ddargparse
  repository: https://github.com/koesterlab/ddargparse
  documentation: https://github.com/koesterlab/ddargparse

extra:
  recipe-maintainers:
    - johanneskoester
